main/home/urls.py
from django.urls import path
from home import views
from django.shortcuts import redirect
from django.urls import reverse

urlpatterns = [
    path("home/", views.home, name="home_page"),
    path("", lambda request:redirect (reverse("home_page"))),
]

main/likes/urls.py
from django.urls import path, include
from django.urls.resolvers import URLPattern

from .views import AddLikeView, RemoveLikeView

app_name = "likes"

urlpatterns = [
    path("add/", AddLikeView.as_view(), name="add"),
    path("remove/", RemoveLikeView.as_view(), name="remove"),
]

main/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("user.urls")),
    path("catalog/", include("catalog.urls")),
    path("private/", include("private.urls")),
    path("likes/", include("likes.urls")),
    path("", include("home.urls")),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/likes/models.py
from django.db import models
from django.conf import settings
from django.db.models.fields import BooleanField
from django.utils import timezone
from private.models import Song

class SongLikes(models.Model):
    song_post = models.ForeignKey(
        Song,
        on_delete = models.CASCADE,
        null = True,
        verbose_name = "Song like",
    )
    liked_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete = models.SET_NULL,
        null = True,
        verbose_name = "Liked by",
    )
    like = models.BooleanField(
        "Like",
        default = False,
    )
    created = models.DateTimeField(
        "Date and time",
        default = timezone.now,
    )

    def __str__(self):
        return f'{self.liked_by}: {self.song_post} {self.like}'

main/likes/views.py
from django.shortcuts import redirect, render
from django.urls.base import reverse
from django.views.generic import View
from user.models import User
from private.models import Song
from likes.models import SongLikes

class AddLikeView(View):
    def post(self, request, *args, **kwargs):
        song_post_id = int(request.POST.get('song_post_id'))
        user_id = int(request.POST.get('user_id'))
        url_form = request.POST.get('url_form')

        user_inst = User.objects.get(id = user_id)
        song_post_inst = Song.objects.get(id = song_post_id)

        try:
            song_like_inst = SongLikes.objects.get(song_post = song_post_inst, liked_by = user_inst)
        except Exception as e:
            post_like = SongLikes(song_post = song_post_inst, liked_by = user_inst, like = True)
            post_like.save()

        return redirect(url_form)

class RemoveLikeView(View):
    def post(self, request, *args, **kwargs):
        song_likes_id = int(request.POST.get('song_likes_id'))
        url_form = request.POST.get('url_form')

        song_like = SongLikes.objects.get(id = song_likes_id)
        song_like.delete()

        return redirect(url_form)

main/likes/templates/add_like.html
{% load likes_song %}

{% is_liked song_post_id as is_liked_bool %}
{% count_likes song_post_id as likes_counter %}

{% if is_liked_bool %}
    {% song_likes_id song_post_id as song_likes_id %}
{% endif %}

<form action="{% if not is_liked_bool %}{% url 'likes:add' %}{% else %}{% url 'likes:remove' %}{% endif %}" method="POST">{% csrf_token %}
    <input type="hidden" name="song_post_id" value="{{ song_post_id }}">
    <input type="hidden" name="user_id" value="{% if user.is_authenticated %}{{ request.user.id }}{% else %}None{% endif %}">
    <input type="hidden" name="url_form" value="{{ request.path }}">

    {% if is_liked_bool %}
        <input type="hidden" name="song_likes_id" value="{{ song_likes_id }}">
    {% endif %}
    <button type="submit">
        {% if not is_liked_bool %}
            <i class="fa fa-heart text-muted"></i>
        {% else %}
            <i class="fa fa-heart text-muted"></i>
        {% endif %}
        <span class="likes-qtu"></span>{{ likes_counter }}</span>
    </button>
</form>

main/likes/templates/add_like_blog.html
{% load likes_song %}

{% is_liked song_post_id as is_liked_bool %}
{% count_likes song_post_id as likes_counter %}

{% if is_liked_bool %}
    {% song_likes_id song_post_id as song_likes_id %}
{% endif %}

<form action="{% if not is_liked_bool %}{% url 'likes:add' %}{% else %}{% url 'likes:remove' %}{% endif %}" method="POST">{% csrf_token %}
    <input type="hidden" name="song_post_id" value="{{ song_post_id }}">
    <input type="hidden" name="user_id" value="{% if user.is_authenticated %}{{ request.user.id }}{% else %}None{% endif %}">
    <input type="hidden" name="url_form" value="{{ request.path }}">

    {% if is_liked_bool %}
        <input type="hidden" name="song_likes_id" value="{{ song_likes_id }}">
    {% endif %}
    <button type="submit">
        {% if not is_liked_bool %}
            <i class="fa fa-heart text-muted"></i>
        {% else %}
            <i class="fa fa-heart text-muted"></i>
        {% endif %}
        <span class="likes-qtu">{{ likes_counter }}</span>
    </button>
</form>